'use client';
import {useState,useEffect} from 'react';
type Repo={id:number,name:string,status:string};
export default function Page(){
const [repos,setRepos]=useState<Repo[]>([]),[repo,setRepo]=useState(''),[path,setPath]=useState('/workspace/project'),[q,setQ]=useState('Where is authentication implemented?'),[result,setResult]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
const [signedIn,setSignedIn]=useState(false),[username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[url,setUrl]=useState(''),[ref,setRef]=useState('main'),[command,setCommand]=useState('python3 -m pytest -q'),[status,setStatus]=useState<Record<string,unknown>>({});
async function call(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok){if(r.status===401)setSignedIn(false);throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data));}return data;}
async function refresh(){const data=await call('/api/repositories');setRepos(data);setSignedIn(true);setStatus(await call('/api/settings/status'));if(data.length)setRepo(String(data[data.length-1].id));}
useEffect(()=>{void refresh().catch(()=>{});},[]);
async function action(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
async function index(){await action(async()=>{setResult(await call('/api/repositories',{name:path.split('/').pop(),path}));await refresh();});}
async function upload(file:File){await action(async()=>{const response=await fetch('/api/repositories/upload',{method:'POST',headers:{'Content-Type':'application/zip'},body:file});const data=await response.json();if(!response.ok)throw Error(data.detail);setResult(data);await refresh();});}
async function run(mode:string){await action(async()=>{setResult(await call(`/api/repositories/${repo}/${mode}`,mode==='graph'?undefined:{question:q,command:command.split(/\s+/),timeout_seconds:120}));});}
if(!signedIn)return <main style={{display:'block',maxWidth:600,margin:'60px auto'}}><section><h1>CodePilot</h1><p>Sign in to your repository workspace.</p><form onSubmit={e=>{e.preventDefault();void action(async()=>{await call('/auth/login',{username,password});setPassword('');await refresh();});}}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button></form>{error&&<p role="alert">{error}</p>}</section></main>;
return <main><aside><div className="brand">CodePilot</div><p>Repository workspace</p><select aria-label="Repository" value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(r=><option key={r.id} value={r.id}>{r.name} · {r.status}</option>)}</select><h3>Connect GitHub</h3><input aria-label="GitHub URL" placeholder="https://github.com/owner/repo" value={url} onChange={e=>setUrl(e.target.value)}/><input aria-label="Branch or revision" value={ref} onChange={e=>setRef(e.target.value)}/><button disabled={busy||!url} onClick={()=>action(async()=>{setResult(await call('/api/repositories/github',{url,ref}));await refresh();})}>Import public repository</button><h3>Upload ZIP</h3><input aria-label="Upload repository ZIP" type="file" accept=".zip" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/><details><summary>Mounted source</summary><input aria-label="Repository path" value={path} onChange={e=>setPath(e.target.value)}/><button disabled={busy} onClick={index}>Index directory</button></details><p>{status.llm_configured?'LLM connected':'LLM key not configured'}</p><p>Embeddings: {String(status.embedding_model||'')}</p><button onClick={()=>action(async()=>{await call('/auth/logout',{});setSignedIn(false);setResult(null);})}>Sign out</button></aside><section><header><div><p>AST • DEPENDENCIES • CITATIONS</p><h1>Understand the whole codebase.</h1></div></header><div className="ask"><textarea aria-label="Question" value={q} onChange={e=>setQ(e.target.value)}/><label>Test command<input aria-label="Test command" value={command} onChange={e=>setCommand(e.target.value)}/></label><p className="hint">Generate & test runs baseline and proposed code in separate, network-isolated containers. Source files remain unchanged.</p><div className="examples">{[['query','Ask repository'],['plan','Plan feature'],['propose','Generate & test'],['graph','Dependencies']].map(([a,label])=><button disabled={busy||!repo||(a==='propose'&&!status.llm_configured)} key={a} onClick={()=>run(a)}>{label}</button>)}</div></div>{busy&&<p role="status">Processing… Imports and tests may take a few minutes.</p>}{error&&<p role="alert">{error}</p>}{result&&<article><h2>Result</h2>{Boolean(result.answer)&&<pre>{String(result.answer)}</pre>}{Boolean(result.explanation)&&<pre>{String(result.explanation)}</pre>}{Boolean(result.diff)&&<pre>{String(result.diff)}</pre>}<pre>{JSON.stringify(Object.fromEntries(Object.entries(result).filter(([k])=>!['answer','explanation','diff'].includes(k))),null,2)}</pre></article>}</section></main>;
}
