'use client';
import {useState,useEffect} from 'react';
type Repo={id:number,name:string,status:string};
export default function Page(){
const [repos,setRepos]=useState<Repo[]>([]),[repo,setRepo]=useState(''),[path,setPath]=useState('/workspace/project'),[q,setQ]=useState('Where is authentication implemented?'),[result,setResult]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function call(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data));return data;}
async function refresh(){try{const data=await call('/api/repositories');setRepos(data);if(data.length)setRepo(String(data[0].id));}catch(e){setError(String(e));}}
useEffect(()=>{void refresh();},[]);
async function index(){setBusy(true);setError('');try{await call('/api/repositories',{name:path.split('/').pop(),path});await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
async function run(action:string){setBusy(true);setError('');try{setResult(await call(`/api/repositories/${repo}/${action}`,action==='graph'?undefined:{question:q}));}catch(e){setError(String(e));}finally{setBusy(false);}}
return <main><aside><div className="brand">CodePilot</div><p>Repository intelligence</p><select aria-label="Repository" value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(r=><option key={r.id} value={r.id}>{r.name} · {r.status}</option>)}</select><p>Index mounted repository</p><input aria-label="Repository path" value={path} onChange={e=>setPath(e.target.value)}/><button disabled={busy} onClick={index}>Index repository</button><p>Mount source in /workspace to begin.</p></aside><section><header><div><p>AST • DEPENDENCIES • CITATIONS</p><h1>Understand the whole codebase.</h1></div></header><div className="ask"><textarea aria-label="Question" value={q} onChange={e=>setQ(e.target.value)}/><div className="examples">{[['query','Ask repository'],['plan','Plan feature'],['propose','Generate diff'],['graph','Show dependencies']].map(([a,label])=><button disabled={busy||!repo} key={a} onClick={()=>run(a)}>{label}</button>)}</div></div>{busy&&<p>Processing…</p>}{error&&<p role="alert">{error}</p>}{result&&<article><h2>Result</h2>{Boolean(result.answer)&&<pre>{String(result.answer)}</pre>}{Boolean(result.explanation)&&<pre>{String(result.explanation)}</pre>}{Boolean(result.diff)&&<pre>{String(result.diff)}</pre>}<pre>{JSON.stringify(Object.fromEntries(Object.entries(result).filter(([k])=>!['answer','explanation','diff'].includes(k))),null,2)}</pre></article>}</section></main>;
}
